name: Test Curl Commit Workflow v2

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello from Curl v2
      run: echo "Committed via FastAPI using Curl v2!"